set nocompatible

" I don't like config file to be directly in the home dir
set viminfofile=~/.config/vim/viminfo
set runtimepath=~/.config/vim/vim,/var/lib/vim/addons,/etc/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim90,/usr/share/vim/vimfiles/after,/etc/vim/after,/var/lib/vim/addons/after

syntax on " Enable syntax higlighting

set wildmenu " Improved command line completion
set title  " Vim update terminal title
set number " Show line number
set wrap   " Enable line wrap
" set textwidth=119 " Wrap on col 120
set showmatch " Show matching brackets when text indicator is over them

" Search 
set ignorecase " Ignore case
set smartcase  " Ignore case unless a cap letter exists in the pattern
set incsearch  " Move to matched string  
set hlsearch   " Highlight found strings

" Indentation style
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2

set encoding=utf8 " Set utf8 as standard encoding 
set ffs=unix " Use Unix as the standard file type

set laststatus=2 " Always(2) have a status line
set noshowmode " Don't duplicate mode information (lastatus=2)

filetype plugin on " Load plugins based on detected filetype
filetype indent on " Load indent configuration based on detected filetype

call plug#begin()

Plug 'arcticicestudio/nord-vim'
Plug 'dense-analysis/ale'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-endwise', { 'for': 'lua' }

call plug#end()

map <C-f> :Rg<CR>
map <C-p> :GFiles<CR>
map <C-]> :ALEGoToDefinition<CR>

let g:ale_linters = {'c': ['clangd'], 'cpp': ['clangd'], 'rust': ['analyzer']}
let g:ale_c_clangd_options = '--enable-config --clang-tidy'
let g:ale_cpp_clangd_options = '--enable-config --clang-tidy'
let g:ale_completion_enabled = 1
let g:ale_sign_column_always = 1

colorscheme nord
